"""Unit tests for SQLModel database models."""
from __future__ import annotations

import uuid
from datetime import UTC, datetime

import pytest
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import AgentStatus, Task, TaskStatus, User


# ---------------------------------------------------------------------------
# Enum value tests
# ---------------------------------------------------------------------------
class TestTaskStatusEnum:
    def test_values_are_strings(self) -> None:
        assert TaskStatus.PENDING == "pending"
        assert TaskStatus.PLANNING == "planning"
        assert TaskStatus.EXECUTING == "executing"
        assert TaskStatus.CRITIQUING == "critiquing"
        assert TaskStatus.COMPLETED == "completed"
        assert TaskStatus.FAILED == "failed"

    def test_usable_in_string_context(self) -> None:
        # StrEnum members compare equal to their string value directly.
        assert f"{TaskStatus.PENDING}" == "pending"
        assert f"status={TaskStatus.COMPLETED}" == "status=completed"

    def test_all_members_present(self) -> None:
        members = {s.value for s in TaskStatus}
        assert members == {"pending", "planning", "executing", "critiquing", "completed", "failed"}


class TestAgentStatusEnum:
    def test_values_are_strings(self) -> None:
        assert AgentStatus.IDLE == "idle"
        assert AgentStatus.RUNNING == "running"
        assert AgentStatus.DONE == "done"
        assert AgentStatus.ERROR == "error"

    def test_all_members_present(self) -> None:
        members = {s.value for s in AgentStatus}
        assert members == {"idle", "running", "done", "error"}


# ---------------------------------------------------------------------------
# User model defaults
# ---------------------------------------------------------------------------
class TestUserModel:
    def test_id_is_uuid_string(self) -> None:
        user = User(
            email="a@b.com",
            username="a",
            hashed_password="hash",
        )
        # id is generated by default_factory
        assert isinstance(user.id, str)
        parsed = uuid.UUID(user.id)
        assert str(parsed) == user.id

    def test_two_users_get_different_ids(self) -> None:
        u1 = User(email="a@b.com", username="a", hashed_password="h")
        u2 = User(email="b@c.com", username="b", hashed_password="h")
        assert u1.id != u2.id

    def test_is_active_defaults_to_true(self) -> None:
        user = User(email="x@y.com", username="x", hashed_password="h")
        assert user.is_active is True

    def test_created_at_is_utc_datetime(self) -> None:
        user = User(email="t@u.com", username="t", hashed_password="h")
        assert isinstance(user.created_at, datetime)
        assert user.created_at.tzinfo is not None

    def test_tasks_relationship_starts_empty(self) -> None:
        user = User(email="r@s.com", username="r", hashed_password="h")
        # Relationship list is not loaded until DB access; in-memory it's empty list.
        assert user.tasks == []


# ---------------------------------------------------------------------------
# Task model defaults
# ---------------------------------------------------------------------------
class TestTaskModel:
    def test_id_is_uuid_string(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert isinstance(task.id, str)
        uuid.UUID(task.id)  # raises if not valid UUID

    def test_two_tasks_get_different_ids(self) -> None:
        t1 = Task(title="a", description="d", user_id="u")
        t2 = Task(title="b", description="d", user_id="u")
        assert t1.id != t2.id

    def test_status_defaults_to_pending(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert task.status == TaskStatus.PENDING

    def test_iteration_count_defaults_to_zero(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert task.iteration_count == 0

    def test_agent_output_fields_default_to_none(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert task.planner_output is None
        assert task.executor_output is None
        assert task.critic_output is None
        assert task.final_result is None

    def test_score_and_error_fields_default_to_none(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert task.critic_score is None
        assert task.error_message is None
        assert task.completed_at is None

    def test_category_is_optional(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert task.category is None

    def test_created_at_and_updated_at_are_set(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert isinstance(task.created_at, datetime)
        assert isinstance(task.updated_at, datetime)

    def test_created_at_is_utc(self) -> None:
        task = Task(title="t", description="d", user_id="u")
        assert task.created_at.tzinfo is not None


# ---------------------------------------------------------------------------
# DB persistence — requires the in-memory session fixture from conftest.
# ---------------------------------------------------------------------------
@pytest.mark.asyncio
async def test_user_persisted_and_retrieved(db_session: AsyncSession) -> None:
    user = User(
        email="persist@test.com",
        username="persist_user",
        hashed_password="hashed_pw",
    )
    db_session.add(user)
    await db_session.commit()

    result = await db_session.execute(
        select(User).where(User.email == "persist@test.com")
    )
    fetched = result.scalar_one()
    assert fetched.id == user.id
    assert fetched.username == "persist_user"
    assert fetched.is_active is True


@pytest.mark.asyncio
async def test_task_persisted_with_user_foreign_key(db_session: AsyncSession) -> None:
    user = User(email="owner@test.com", username="owner", hashed_password="h")
    db_session.add(user)
    await db_session.commit()

    task = Task(
        title="my task",
        description="do something useful here",
        user_id=user.id,
        category="Research",
    )
    db_session.add(task)
    await db_session.commit()

    result = await db_session.execute(select(Task).where(Task.user_id == user.id))
    fetched = result.scalar_one()
    assert fetched.title == "my task"
    assert fetched.status == TaskStatus.PENDING
    assert fetched.category == "Research"


@pytest.mark.asyncio
async def test_task_status_can_be_updated(db_session: AsyncSession) -> None:
    user = User(email="upd@test.com", username="upd", hashed_password="h")
    db_session.add(user)
    await db_session.commit()

    task = Task(title="t", description="d", user_id=user.id)
    db_session.add(task)
    await db_session.commit()

    task.status = TaskStatus.COMPLETED
    task.final_result = "## Done"
    task.critic_score = 0.88
    task.completed_at = datetime.now(UTC)
    await db_session.commit()
    await db_session.refresh(task)

    assert task.status == TaskStatus.COMPLETED
    assert task.final_result == "## Done"
    assert task.critic_score == pytest.approx(0.88)
    assert task.completed_at is not None


@pytest.mark.asyncio
async def test_cascade_delete_removes_tasks_with_user(db_session: AsyncSession) -> None:
    user = User(email="cascade@test.com", username="cascade_u", hashed_password="h")
    db_session.add(user)
    await db_session.commit()

    task = Task(title="t", description="will be cascade-deleted", user_id=user.id)
    db_session.add(task)
    await db_session.commit()
    task_id = task.id

    await db_session.delete(user)
    await db_session.commit()

    orphaned = await db_session.get(Task, task_id)
    assert orphaned is None


@pytest.mark.asyncio
async def test_multiple_tasks_per_user(db_session: AsyncSession) -> None:
    user = User(email="multi@test.com", username="multi_u", hashed_password="h")
    db_session.add(user)
    await db_session.commit()

    tasks = [
        Task(title=f"task-{i}", description=f"description {i}", user_id=user.id)
        for i in range(3)
    ]
    db_session.add_all(tasks)
    await db_session.commit()

    result = await db_session.execute(select(Task).where(Task.user_id == user.id))
    fetched = result.scalars().all()
    assert len(fetched) == 3
